### ISSUE TITLE
Twitch.listen is never triggered ?

### ISSUE THREAD

**Issue by Tilkeii** [twitchdev/extensions-hello-world#2]
https://github.com/twitchdev/extensions-hello-world/blob/500ad0d0f0c908d48c64eb170cbf8ed9941a814f/public/viewer.js#L72

Hi,

I tried to test this example but there is something i don't get it. Why this line above is never triggered ?
And because this is never triggered, the circle don't update when there is multiple clients.

**Comment by affinity-matrix** [comment]
Hey @Tilkeii,

I'm wondering if you're experiencing a configuration error. I've seen this issue come up, but it's usually due to a missing parameter. I would suggest double-checking the provided command line arguments (or environment variables). If that's no help, let me know!

_reference:_ https://github.com/twitchdev/extensions-hello-world/blob/master/README.md#configuring-and-running-the-extension-backend-service

**Comment by Tilkeii** [comment]
I checked my parameters and it seems ok.

here the part in my cmd script for the EBS part. I tried with both command.

```bash
echo [91m Starting extension backend service [0m
::start cmd /k node services/backend -c vl5y7ow6gh04t2o94z3kk4loexxxxx -s fhztOFj5vkKXCCbrtRbiKGZyPve7UeNiOWyuaIlUxxxx -o 10196xxxx
SET EXT_CLIENT_ID=vl5y7ow6gh04t2o94z3kk4loesxxxx
SET EXT_SECRET=fhztOFj5vkKXCCbrtRbiKGZyPve7UeNiOWyuaIlUxxxx
SET EXT_OWNER_ID=10196xxxx
start cmd /k node services/backend
```

i don't have any error in terminal or in browser console about this problem

**Comment by Tilkeii** [comment]
problem solved

see https://discuss.dev.twitch.tv/t/twitch-listen-is-never-triggered/15030/6?u=tilkeii
